# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_data import UserData  # noqa: F401,E501
from swagger_server import util


class RequestRegisterUserByAdmin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, external_transaction_id: str=None, data: UserData=None):  # noqa: E501
        """RequestRegisterUserByAdmin - a model defined in Swagger

        :param channel: The channel of this RequestRegisterUserByAdmin.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestRegisterUserByAdmin.  # noqa: E501
        :type external_transaction_id: str
        :param data: The data of this RequestRegisterUserByAdmin.  # noqa: E501
        :type data: UserData
        """
        self.swagger_types = {
            'channel': str,
            'external_transaction_id': str,
            'data': UserData
        }

        self.attribute_map = {
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId',
            'data': 'data'
        }
        self._channel = channel
        self._external_transaction_id = external_transaction_id
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RequestRegisterUserByAdmin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestRegisterUserByAdmin of this RequestRegisterUserByAdmin.  # noqa: E501
        :rtype: RequestRegisterUserByAdmin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestRegisterUserByAdmin.


        :return: The channel of this RequestRegisterUserByAdmin.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestRegisterUserByAdmin.


        :param channel: The channel of this RequestRegisterUserByAdmin.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestRegisterUserByAdmin.


        :return: The external_transaction_id of this RequestRegisterUserByAdmin.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestRegisterUserByAdmin.


        :param external_transaction_id: The external_transaction_id of this RequestRegisterUserByAdmin.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def data(self) -> UserData:
        """Gets the data of this RequestRegisterUserByAdmin.


        :return: The data of this RequestRegisterUserByAdmin.
        :rtype: UserData
        """
        return self._data

    @data.setter
    def data(self, data: UserData):
        """Sets the data of this RequestRegisterUserByAdmin.


        :param data: The data of this RequestRegisterUserByAdmin.
        :type data: UserData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
