# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseResetPasswordData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code_email: str=None):  # noqa: E501
        """ResponseResetPasswordData - a model defined in Swagger

        :param code_email: The code_email of this ResponseResetPasswordData.  # noqa: E501
        :type code_email: str
        """
        self.swagger_types = {
            'code_email': str
        }

        self.attribute_map = {
            'code_email': 'code_email'
        }
        self._code_email = code_email

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseResetPasswordData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseResetPassword_data of this ResponseResetPasswordData.  # noqa: E501
        :rtype: ResponseResetPasswordData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_email(self) -> str:
        """Gets the code_email of this ResponseResetPasswordData.


        :return: The code_email of this ResponseResetPasswordData.
        :rtype: str
        """
        return self._code_email

    @code_email.setter
    def code_email(self, code_email: str):
        """Sets the code_email of this ResponseResetPasswordData.


        :param code_email: The code_email of this ResponseResetPasswordData.
        :type code_email: str
        """

        self._code_email = code_email
