# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SigninData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code_email: str=None, password: str=None):  # noqa: E501
        """SigninData - a model defined in Swagger

        :param code_email: The code_email of this SigninData.  # noqa: E501
        :type code_email: str
        :param password: The password of this SigninData.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'code_email': str,
            'password': str
        }

        self.attribute_map = {
            'code_email': 'code_email',
            'password': 'password'
        }
        self._code_email = code_email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'SigninData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SigninData of this SigninData.  # noqa: E501
        :rtype: SigninData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_email(self) -> str:
        """Gets the code_email of this SigninData.


        :return: The code_email of this SigninData.
        :rtype: str
        """
        return self._code_email

    @code_email.setter
    def code_email(self, code_email: str):
        """Sets the code_email of this SigninData.


        :param code_email: The code_email of this SigninData.
        :type code_email: str
        """

        self._code_email = code_email

    @property
    def password(self) -> str:
        """Gets the password of this SigninData.


        :return: The password of this SigninData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this SigninData.


        :param password: The password of this SigninData.
        :type password: str
        """

        self._password = password
