# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SignupData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code_email: str=None, name: str=None, last_name: str=None, password: str=None):  # noqa: E501
        """SignupData - a model defined in Swagger

        :param code_email: The code_email of this SignupData.  # noqa: E501
        :type code_email: str
        :param name: The name of this SignupData.  # noqa: E501
        :type name: str
        :param last_name: The last_name of this SignupData.  # noqa: E501
        :type last_name: str
        :param password: The password of this SignupData.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'code_email': str,
            'name': str,
            'last_name': str,
            'password': str
        }

        self.attribute_map = {
            'code_email': 'code_email',
            'name': 'name',
            'last_name': 'last_name',
            'password': 'password'
        }
        self._code_email = code_email
        self._name = name
        self._last_name = last_name
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'SignupData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SignupData of this SignupData.  # noqa: E501
        :rtype: SignupData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_email(self) -> str:
        """Gets the code_email of this SignupData.


        :return: The code_email of this SignupData.
        :rtype: str
        """
        return self._code_email

    @code_email.setter
    def code_email(self, code_email: str):
        """Sets the code_email of this SignupData.


        :param code_email: The code_email of this SignupData.
        :type code_email: str
        """

        self._code_email = code_email

    @property
    def name(self) -> str:
        """Gets the name of this SignupData.


        :return: The name of this SignupData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SignupData.


        :param name: The name of this SignupData.
        :type name: str
        """

        self._name = name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this SignupData.


        :return: The last_name of this SignupData.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this SignupData.


        :param last_name: The last_name of this SignupData.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def password(self) -> str:
        """Gets the password of this SignupData.


        :return: The password of this SignupData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this SignupData.


        :param password: The password of this SignupData.
        :type password: str
        """

        self._password = password
